### ISSUE TITLE
Ansile Failed to Configure LearningLocker database's configuration details

### ISSUE THREAD

**Issue by NFH26** [davidpesce/learninglocker-v1-dev-env#1]
Greetings, 

I followed the instructions given here which are well written, I would appreciate if anyone can help me with this issue. when I run `Vagrant up` and it reaches the task: 

> Configure LearningLocker database's configuration details 

it throws an exception saying 

> "msg": "Path /var/www/learninglocker/app/config/local/database.php does not exist !"
I SSH the server and found that there is no database.php in that directory. I removed everything and redid the installation and it shows the same error. Could anyone help? 

![ll installing db error](https://cloud.githubusercontent.com/assets/5903732/26284139/e2214ee0-3e3c-11e7-9bb0-981459c5fb2d.png)

Regards, 
~Nayef

**Comment by davidpesce** [comment]
Hi, Nayef. There are two locations for the database.php file ( this is because of a legacy location). The failure doesn't mean the entire script failed, it just means that location isn't there. I've toyed with the idea of getting rid of it, but it shouldn't impact performance and I can still use it on old versions of LL.
